server:
  port: 8091

spring:
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3307/jpa_study?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: hello
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          redisson:
            fallback: true
            config: redisson.yaml
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
        format_sql: true
        generate_statistics: true

logging:
  level:
    org.springframework.cache: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.hibernate.cache.internal: debug
    org.hibernate.cache.spi: debug
