server:
  port: 8091
  
spring:
  application:
    name: demo



  datasource:
    url: jdbc:mysql://localhost:3307/jpa_study?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: hello
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.redisson.hibernate.RedissonRegionFactory
          # Redisson ??? application.yml ?? ?? ??
          cache_provider_settings:
            config: "classpath:redisson-config.yml"  # ??? ?? ??

  cache:
    type: redis

  redisson:
    single-server:
      address: "redis://localhost:6379"

logging:
  level:
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
